---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: fastapi
          image: sakit333/fastapi-observability:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

          # 🔥 Load ALL env from .env.docker via Secret
          envFrom:
            - secretRef:
                name: app-secrets

          # 🔥 Health checks (production standard)
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20

          # 🔥 Resource limits (important in real world)
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: logs
              mountPath: /app/logs

      volumes:
        - name: logs
          hostPath:
            path: /tmp/app-logs
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007   # optional fixed port (or remove this line)
  type: NodePort