---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "fastapi"
        static_configs:
          - targets: ["fastapi-service:80"]
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:3000']
      - job_name: 'loki'
        static_configs:
          - targets: ['loki:3100']
      - job_name: 'tempo'
        static_configs:
          - targets: ['tempo:3200']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=7d"

          ports:
            - containerPort: 9090

          # ❤️ Health checks
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 20

          # 💾 Storage
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus

          # ⚡ Resources
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30009   # optional fixed port
  type: NodePort