{
 "title": "FastAPI Logs (Loki)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"app-logs\"}"
    }
   ]
  },
  {
   "title": "Total Error Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count_over_time({job=\"app-logs\"} | json | levelname=\"ERROR\" [$__range])"
    }
   ]
  },
  {
   "title": "Total Warning Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "count_over_time({job=\"app-logs\"} | json | levelname=\"WARNING\" [$__range])"
    }
   ]
  },
  {
   "title": "Total Info Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "count_over_time({job=\"app-logs\"} | json | levelname=\"INFO\" [$__range])"
    }
   ]
  },
  {
   "title": "Error Logs Stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"app-logs\"} | json | levelname=\"ERROR\""
    }
   ]
  },
  {
   "title": "Trace-linked Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"app-logs\"} | json | trace_id!=\"\""
    }
   ]
  }
 ]
}