{
 "title": "FastAPI Metrics (Prometheus)",
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(request_count_total[1m])", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Endpoint Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(demo_info_count_total[1m])",
     "legendFormat": "Info"
    },
    {
     "expr": "rate(demo_error_count_total[1m])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "request_count_total" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "demo_error_count_total" }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(demo_error_count_total[1m]) / rate(request_count_total[1m]) * 100"
    }
   ]
  },
  {
   "title": "Average Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(demo_work_duration_seconds_sum[1m]) / rate(demo_work_duration_seconds_count[1m])",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(demo_work_duration_seconds_bucket[1m]))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory" }
   ]
  }
 ]
}